[package]
name = "sorting_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sorting_modules"
path = "src/lib.rs"

[[bin]]
name = "sorting_visualizer"
path = "src/bin/bin.rs"

[dependencies]